{"name": "Validate Reset Button", "status": "broken", "statusDetails": {"message": "TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not int", "trace": "self = <tests.sidebar_test.TestSidebar object at 0x000001E8B8D50AC0>\nsetup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"ed757e1100f6196c6bc1a2882cceedd4\")>\nlogin_page = <pages.login_page.LoginPage object at 0x000001E8B8D81FC0>\nsidebar_page = <pages.sidebar_page.SideBarPage object at 0x000001E8B8D81060>\nproducts_page = <pages.products_page.ProductsPage object at 0x000001E8B8D83E80>\ncart_page = <pages.cart_page.CartPage object at 0x000001E8B8D83C10>\n\n    @allure.title(\"Validate Reset Button\")\n    @allure.description(\"This test validates the app reset functionality.\")\n    def test_03_app_reset_functionality(self, setup, login_page, sidebar_page, products_page, cart_page):\n        login_page.fill_info(self.valid_username, self.valid_password)\n        products_page.add_to_cart(random.randint(1, 6))\n    \n        # Wait until the cart has at least one item\n>       WebDriverWait(sidebar_page.driver, 10).until(\n            EC.text_to_be_present_in_element(\n                products_page.get_cart_count(),\n                \"1\"\n            )\n        )\n\nsidebar_test.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:96: in until\n    value = method(self._driver)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"ed757e1100f6196c6bc1a2882cceedd4\")>\n\n    def _predicate(driver: WebDriverOrWebElement):\n        try:\n>           element_text = driver.find_element(*locator).text\nE           TypeError: selenium.webdriver.remote.webdriver.WebDriver.find_element() argument after * must be an iterable, not int\n\n..\\..\\..\\..\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\support\\expected_conditions.py:243: TypeError"}, "description": "This test validates the app reset functionality.", "start": 1740123794655, "stop": 1740123797383, "uuid": "ada71aca-63b4-4aa0-b047-c8bf024f3226", "historyId": "bc4a154de334e7c950254be201313cdb", "testCaseId": "bc4a154de334e7c950254be201313cdb", "fullName": "tests.sidebar_test.TestSidebar#test_03_app_reset_functionality", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "sidebar_test"}, {"name": "subSuite", "value": "TestSidebar"}, {"name": "host", "value": "Assaf"}, {"name": "thread", "value": "29544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.sidebar_test"}]}