{"uuid": "2783741f-e329-4b28-ab5a-be393e944345", "children": ["958e82ca-159a-44ac-8a21-ae56206c064a"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: JavaScript code failed\nfrom unknown command: 'Runtime.evaluate' wasn't found\n  (Session info: chrome=133.0.6943.99)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7EC866EE5+28773]\n\t(No symbol) [0x00007FF7EC7D25D0]\n\t(No symbol) [0x00007FF7EC668FAA]\n\t(No symbol) [0x00007FF7EC6557B8]\n\t(No symbol) [0x00007FF7EC653F62]\n\t(No symbol) [0x00007FF7EC6547AF]\n\t(No symbol) [0x00007FF7EC67F9CB]\n\t(No symbol) [0x00007FF7EC673210]\n\t(No symbol) [0x00007FF7EC6730B9]\n\t(No symbol) [0x00007FF7EC644A72]\n\t(No symbol) [0x00007FF7EC642A03]\n\t(No symbol) [0x00007FF7EC727A81]\n\t(No symbol) [0x00007FF7EC6E724A]\n\t(No symbol) [0x00007FF7EC70F6F3]\n\t(No symbol) [0x00007FF7EC6E7023]\n\t(No symbol) [0x00007FF7EC6AFF5E]\n\t(No symbol) [0x00007FF7EC6B11E3]\n\tGetHandleVerifier [0x00007FF7ECBB422D+3490733]\n\tGetHandleVerifier [0x00007FF7ECBCBA13+3586963]\n\tGetHandleVerifier [0x00007FF7ECBC144D+3544525]\n\tGetHandleVerifier [0x00007FF7EC92C9AA+838442]\n\t(No symbol) [0x00007FF7EC7DD01F]\n\t(No symbol) [0x00007FF7EC7D95E4]\n\t(No symbol) [0x00007FF7EC7D9786]\n\t(No symbol) [0x00007FF7EC7C8CB9]\n\tBaseThreadInitThunk [0x00007FFD6BB27374+20]\n\tRtlUserThreadStart [0x00007FFD6D93CC91+33]\n\n", "trace": "  File \"C:\\Users\\Viola\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Viola\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"C:\\Users\\Viola\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Viola\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Viola\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\Viola\\Downloads\\SauceDemoAutomationProject\\SauceDemoAutomationProject-master\\tests\\conftest.py\", line 17, in setup\n    driver.maximize_window()\n  File \"C:\\Users\\Viola\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 532, in maximize_window\n    self.execute(command, None)\n  File \"C:\\Users\\Viola\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 380, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Viola\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739968142720, "stop": 1739968145882}], "start": 1739968142720, "stop": 1739968146115}